USE [master]
GO

/****** Object:  Database [ToDoApp]    Script Date: 9/11/2022 10:04:21 PM ******/
CREATE DATABASE [ToDoApp]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ToDoApp', FILENAME = N'C:\Users\user\ToDoApp.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ToDoApp_log', FILENAME = N'C:\Users\user\ToDoApp_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ToDoApp].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ToDoApp] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ToDoApp] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ToDoApp] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ToDoApp] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ToDoApp] SET ARITHABORT OFF 
GO

ALTER DATABASE [ToDoApp] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ToDoApp] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ToDoApp] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ToDoApp] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ToDoApp] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ToDoApp] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ToDoApp] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ToDoApp] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ToDoApp] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ToDoApp] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ToDoApp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ToDoApp] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ToDoApp] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ToDoApp] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ToDoApp] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ToDoApp] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ToDoApp] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ToDoApp] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ToDoApp] SET  MULTI_USER 
GO

ALTER DATABASE [ToDoApp] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ToDoApp] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ToDoApp] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ToDoApp] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ToDoApp] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ToDoApp] SET QUERY_STORE = OFF
GO

USE [ToDoApp]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [ToDoApp] SET  READ_WRITE 
GO